# Generated by Django 5.1.4 on 2025-02-12 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='isCheated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='leaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.application')),
            ],
        ),
    ]
