# Generated by Django 5.1.4 on 2025-02-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_application_completed_alter_application_ischeated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='./orgs'),
        ),
    ]
