# Generated by Django 5.1.4 on 2025-02-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customconversation',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
