# Generated by Django 5.1.4 on 2025-02-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_application_approved_application_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='Photo',
            new_name='photo',
        ),
    ]
