# Generated by Django 5.1.4 on 2025-02-14 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_rename_photo_organization_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postings',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
