# Generated by Django 5.1.4 on 2025-02-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_postings_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
