# Generated by Django 5.1.4 on 2025-02-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_application_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='application',
            name='score',
        ),
        migrations.AddField(
            model_name='application',
            name='virtualResume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InterviewChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.CharField(choices=[('resume', 'Resume Questions'), ('cp', 'Competitive Programming'), ('dev_skills', 'Development Skills'), ('completed', 'Interview Completed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.application')),
            ],
        ),
        migrations.CreateModel(
            name='ChatQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.interviewchat')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.JSONField()),
                ('cp_skills', models.JSONField()),
                ('dev_skills', models.JSONField()),
                ('consistency_score', models.FloatField()),
                ('correctness_score', models.FloatField()),
                ('overall_rating', models.FloatField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.interviewchat')),
            ],
        ),
    ]
