# Generated by Django 5.1.4 on 2025-02-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_remove_application_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewchat',
            name='application',
        ),
        migrations.RemoveField(
            model_name='virtualresume',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='application',
            name='virtualResume',
        ),
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ChatQuestion',
        ),
        migrations.DeleteModel(
            name='InterviewChat',
        ),
        migrations.DeleteModel(
            name='VirtualResume',
        ),
    ]
