# Generated by Django 5.1.4 on 2025-02-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_remove_interviewchat_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='extratedResume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
