# Generated by Django 5.1.4 on 2025-02-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_application_extratedresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='virtualResume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='resumeconvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.application')),
            ],
        ),
        migrations.CreateModel(
            name='resquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user', max_length=100)),
                ('question', models.TextField(default='Default question text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.resumeconvo')),
            ],
        ),
    ]
