# Generated by Django 5.1.4 on 2025-02-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_custominterviews_dsa_custominterviews_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='standardized_resume',
            field=models.FileField(blank=True, null=True, upload_to='standardized_resumes/'),
        ),
    ]
