# Generated by Django 5.1.4 on 2025-02-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_application_standardized_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='standardized_resume',
            field=models.FileField(blank=True, null=True, upload_to='std_resumes/'),
        ),
    ]
