# Generated by Django 5.1.4 on 2025-01-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='group',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.DeleteModel(
            name='chatGroup',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
