name: Analyze PR or Push
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened] 
jobs:
  analyze_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Send PR analysis request
        env:
          # Store this securely in GitHub secrets
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          # Use the built-in GITHUB_TOKEN for API access
          GH_TOKEN: ${{ secrets.GITHUBSS_TOKEN }}
        run: |
          # Extract PR number from event context
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            PR_NUM="${{ github.event.pull_request.number }}"
          else
            # If it's a push event, you might want to handle differently
            PR_NUM="0"
          fi
          
          # Debug what we're sending
          echo "Sending analysis request for PR #$PR_NUM"
          
          # Use the correct Authorization header format for DRF
          curl -v -X POST "http://20.97.210.43:8000/start-task/" \
          -H "Content-Type: application/json" \
          -H "Authorization: Token $AUTH_TOKEN" \
          -d "{\"repo_url\":\"https://github.com/${{ github.repository }}\",\"pr_num\":\"$PR_NUM\",\"github_token\":\"$GH_TOKEN\"}" 2>&1 | tee curl_output.log
          
          # Display curl exit code
          echo "Curl exit code: $?"
