name: Send PR analysis request
  env:
    # Store this securely in GitHub secrets
    AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    # Use the built-in GITHUB_TOKEN for API access
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    # Extract PR number from event context
    if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
      PR_NUM="${{ github.event.pull_request.number }}"
    else
      # If it's a push event, you might want to handle differently
      PR_NUM="0"
    fi
    
    # Create a JSON file to avoid escaping issues
    echo '{
      "repo_url": "https://github.com/${{ github.repository }}",
      "pr_num": "'"$PR_NUM"'",
      "github_token": "'"$GH_TOKEN"'"
    }' > payload.json
    
    # Debug the payload
    echo "Payload contents:"
    cat payload.json
    
    # Send the request with the file as payload
    curl -v -X POST "http://20.97.210.43:8000/start-task/" \
      -H "Content-Type: application/json" \
      -H "Authorization: Token $AUTH_TOKEN" \
      --data @payload.json
