name: Analyze PR or Push

on: 
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  analyze_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send PR analysis request
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUBSS_TOKEN }}
        run: |
          # Extract PR number from event context
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            PR_NUM="${{ github.event.pull_request.number }}"
          else
            PR_NUM="0"
          fi

          # Create JSON payload
          echo '{}' | jq --arg repo_url "https://github.com/${{ github.repository }}" \
                         --arg pr_num "$PR_NUM" \
                         --arg github_token "$GH_TOKEN" \
                         '.repo_url = $repo_url | .pr_num = $pr_num | .github_token = $github_token' > payload.json

          # Debug the payload
          echo "Payload contents:"
          cat payload.json

          # Send the request
          curl -v -X POST "http://20.97.210.43:8000/start-task/" \
            -H "Content-Type: application/json" \
            -H "Authorization: Token $AUTH_TOKEN" \
            --data @payload.json
