name: Analyze PR or Push

on:
  push:
    branches:
      - main  # Change this to the branch you want to watch (e.g., main or a feature branch)
  pull_request_target:
    types: [opened, synchronize, reopened]  # Triggers when PR is created, synchronized, or reopened

jobs:
  analyze_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python (if needed)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up environment variables
        

      - name: Send POST request to start analysis task
        run: |
          curl -X POST http://127.0.0.1:8000/start-task/ \
          -H "Content-Type: application/json" \
          -H "Authorization: token $AUTH_TOKEN" \
          -d '{
            "repo_url": "https://github.com/sathwikshetty33/InterXAI",
            "pr_num": "1",
            "github_token": "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"
          }'
