- name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests
        run: pip install requests
        
      - name: Send analysis request with Python
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -c "
          import requests
          import json
          import os
          import sys
          
          # Get PR number from GitHub event context
          event_name = '${{ github.event_name }}'
          pr_num = '${{ github.event.pull_request.number }}' if event_name == 'pull_request_target' else '0'
          
          print(f'Sending analysis request for PR #{pr_num}')
          
          # Prepare request data
          data = {
              'repo_url': 'https://github.com/${{ github.repository }}',
              'pr_num': pr_num,
              'github_token': os.environ.get('GH_TOKEN')
          }
          
          # Send request
          try:
              response = requests.post(
                  'http://20.97.210.43:8000/start-task/',
                  headers={
                      'Content-Type': 'application/json',
                      'Authorization': f'token {os.environ.get(\"AUTH_TOKEN\")}'
                  },
                  json=data
              )
              print(f'Status code: {response.status_code}')
              print(f'Response: {response.text}')
              response.raise_for_status()
          except Exception as e:
              print(f'Error: {str(e)}')
              sys.exit(1)
          "
