name: Send PR analysis request
env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUBSS_TOKEN }} # Fix typo if it's GITHUBSS_TOKEN
run: |
  if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
    PR_NUM="${{ github.event.pull_request.number }}"
  else
    PR_NUM="0"
  fi

  echo '{
    "repo_url": "https://github.com/${{ github.repository }}",
    "pr_num": "'"$PR_NUM"'",
    "github_token": "'"$GH_TOKEN"'"
  }' > payload.json

  echo "Payload contents:"
  cat payload.json

  if [[ ! -f payload.json ]]; then
    echo "Error: payload.json not found"
    exit 1
  fi

  curl -v -X POST "http://20.97.210.43:8000/start-task/" \
    -H "Content-Type: application/json" \
    -H "Authorization: Token $AUTH_TOKEN" \
    --data @payload.json || {
      echo "Curl failed with exit code $?"
      exit 1
    }

  echo "Curl exit code: $?"
